### ISSUE TITLE
Release to open source: checklist

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/training-manual#202]
I'm going to share https://github.com/githubtraining/training-manual with the world. The following are items that we need to take care of to get this repository in shape for the open! @githubtraining/trainers, @beardofedu, @amyschoen, if you're able to help with any of these, that would be very helpful 🙇 (cc @matthewmccullough, @BonnieC) 

Before we make this public, we need to complete the following: 

## Coordination

- [x] The repo is visible to the teams below (typically all employees should have read access pre-open-source)
  - In progress: https://github.com/github/entitlements/pull/10424/
- [x] Discuss with `@github/legal` if there are any licensing or other legal concerns.
  - In progress: https://github.com/github/open-source-releases/issues/120
- [x] Discuss with `@github/public-relations` if it make sense to do any press around the release. 
  - In progress: https://github.com/github/open-source-releases/issues/120
- [x] Discuss with `@github/marketing` if it makes sense write about this project on the GitHub blog. 
  - In progress: https://github.com/github/open-source-releases/issues/120
- ~~Open an issue in [github/creative](https://github.com/github/creative/issues/new) to request a snazzy logo~~ We have been using an image from the Octodex for this org and plan to continue with it

## Preparation

- [x] It has a name that is easy to remember, gives some idea what the project does, and does [not conflict with an existing project](http://ivantomic.com/projects/ospnc/) or infringe on any [trademarks](http://www.uspto.gov).
- [x] It uses consistent code conventions, clear function/method/variable names, and a sensible public API.
- [x] The code is clearly commented, documenting intentions and edge cases.
- [x] The distribution mechanism is as convenient, standard, and low-overhead as possible (RubyGems, Homebrew, Bower, Maven, NuGet, etc.).
- [x] I have opened an issue in the [`oss-legal-review` repo](https://github.com/github/oss-legal-review/issues) regarding how we use (or do not use) encryption in this repository. Please put a link to that issue in the comments on this issue.
  - In progress: https://github.com/github/oss-legal-review/issues/382
- [x] There are no sensitive materials in the revision history, issues, or pull requests.
  - If any sensitive content or commit messages are found in commits, consider squashing the revision history.
  - If we wish to preserve sensitive history _or_ we wish the public repo to have zero non-commit history, rename the private repo and create a new blank slate repo with the intended public name and any commit history intended to be public.
- [x] It has a `CONTRIBUTING.md` based on [this template](https://github.com/github/open-source-releases/raw/master/templates/CONTRIBUTING.md). 
  - In progress: https://github.com/githubtraining/training-manual/pull/207
-  ~~`opensource+REPO@github.com` is provided as a maintainer contact (e.g., in the `.gemspec` `email` field for Ruby gems).~~
- [x] It has a `LICENSE`; which one documented at [licenses for GitHub open source projects](https://github.com/github/open-source/blob/master/docs/licensing.md#licenses-for-github-open-source-projects).
  - In progress: https://github.com/githubtraining/training-manual/pull/205
  - [x] All dependencies (including transitive) are under compatible open source licenses ([License Finder](https://github.com/pivotal-legacy/LicenseFinder) may be useful to do a spot check)
  - [x] It is a library/will not be shipped as an application (eg desktop, mobile, or server package), or if it is, it is released with user-available license and credits information (desktop or mobile; see [legal eagle](https://github.com/atom/legal-eagle)) or includes license and credits information for a bill of materials (server; see [licensed](https://github.com/github/licensed)).
- [x] It has a `CODE_OF_CONDUCT.md`; use http://contributor-covenant.org/version/1/4/code-of-conduct.md and fill in opensource@github.com as the email address.
  - In progress: https://github.com/githubtraining/training-manual/pull/206
- [x] It has a `SECURITY.md`; use https://github.com/actions/.github/blob/master/SECURITY.md or equivalent for the org it is being released in.
  - In progress: https://github.com/githubtraining/training-manual/pull/210

## `README.md`

- All in progress: https://github.com/githubtraining/training-manual/pull/212
- [x] It starts with a one-line description that explains what the project is about, who might be interested in it, what language its written in, and how it might be different from similar projects.
- [x] It includes a list of features and limitations.
- [x] It states the goals and scope of the project to help set expectations and filter proposed changes down the line.
- [x] It includes the current status (e.g., proof of concept, used in production, active development, orphaned, etc.)
- [x] It includes a description of the kind of environment required to run the software and instructions for setting it up.
- [x] It clearly states the external dependencies and directions for installing them.
- [x] It includes a high-level development roadmap or link to open issues/milestones.
- [x] It explicitly asks for contributions, if you want them, with a link to `CONTRIBUTING.md`.
- [x] It has a License section that states the license and if _any_ GitHub logos are used, the line ``When using the GitHub logos, be sure to follow the [GitHub logo guidelines](https://github.com/logos).``

## Maintenance

- [x] At least one Hubber is committed to managing community interactions by triaging and responding to issues, giving feedback and merging pull requests, and releasing new versions. **This will be handled by the @githubtraining/programs team as a part of our existing comms duty.**

## Next steps

- [ ] Update the issue in the [github/open-source-releases repository](https://github.com/github/open-source-releases/issues/120) 
- [ ] Make the repository public
- [ ] Change the name of the repository to `github-training-manual`
- [ ] Change the owner to `github`
- [ ] Implement redirection solution (create `training-manual` repository that links via README.md and gh-pages to the new manual?)
- [ ] Change the name

**Comment by brianamarie** [comment]
🎉 🚢
